### ISSUE TITLE
Real Brands

### ISSUE THREAD

**Issue by ewilletts** [elliospizzaman/Drivers-ED#7]
I noticed in the city artwork a few copyrighted companies logos such as pizza hut and pepsi we need to remove them we have not gotten legal permission to use these could get charged with copyright infringement I don't care what we use to replace them but they must not be real life companies of brands.

**Comment by techwcs** [comment]
I think this is fair use for education purposes, but I don't care if Anthony wants to replace them as long as it doesn't delay a finish. 

It's time to finish this thing.

**Comment by ewilletts** [comment]
I will call all of the companies and notify them that we are using their logos just in case.

**Comment by techwcs** [comment]
I think you have more important things to work on, no?

**Comment by elliospizzaman** [comment]
Most of offensive artwork has been removed.
