### ISSUE TITLE
I cannot see the buildings

### ISSUE THREAD

**Issue by ewilletts** [elliospizzaman/Drivers-ED#8]
in the mesh filter component for each building it says missing(mesh) i have maya i have unity 4.6.5 the only thing i can think that would cause the problem is that the models have not been uploaded to github if you could fix this that would help

**Comment by ewilletts** [comment]
I need you to convert the .mb and .ma files to .FBX and then upload them.

**Comment by elliospizzaman** [comment]
This is fixed. There are mesh files in the project instead of mb. Check out the City scene which has lots of models in it. If you still can't see the buildings in the City scene, let me know. I may have added back some of the copyrighted images in the process, but I will get rid of those.
